server.port=8082
spring.application.name=mock-crm-service

# Usar localhost:9093 para dev local; KAFKA_BOOTSTRAP_SERVERS=kafka:9092 quando rodar no Docker
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
mock.crm.initial-leads=10
mock.crm.interaction-interval=15000
mock.crm.stage-advance-interval=60000
